---
- hosts: db
  become: yes

  vars_files:
    - vars/main.yml   

  pre_tasks:
  - name: Update apt cache if needed
    ansible.builtin.package:
      update_cache: true
      cache_valid_time: 3600
  
  - name: Upgrade all packages
    ansible.builtin.package:
      name: "*"
      state: latest

  - name: Ensure Universe Repo is enabled
    apt_repository:
      repo: deb http://archive.ubuntu.com/ubuntu focal universe
      state: present
      update_cache: true

  roles:
    - role: geerlingguy.docker
      docker_users: vagrant
    - geerlingguy.security
    - andrewrothstein.miniconda
    - githubixx.ansible_role_wireguard
    - gantsign.visual-studio-code
    - role: gantsign.antigen
      users:
        - username: "{{ ansible_ssh_user }}"
          antigen_libraries:
            - name: oh-my-zsh
          antigen_them:
            name: agnoster
          antigen_bundles:
            - name: git
            - name: common-aliases
            - name: docker
            - name: zsh-syntax-highlighting
              url: zsh-users/zsh-syntax-highlighting
            - name: zsh-completions
              url: zsh-users/zsh-completions
            - name: zsh-autosuggestions
              url: zsh-users/zsh-autosuggestions

  tasks:
  - name: Ensure ZSH is installed
    ansible.builtin.package:
      name: zsh
      state: present

  - name: Ensure git is installed
    ansible.builtin.package: 
      name: git
      state: present

  - name: Ensure curl is installed
    ansible.builtin.package:
      name: curl
      state: present

  - name: Ensure wget is installed
    ansible.builtin.package:
      name: wget
      state: present

  - name: Ensure FiraCode is installed
    ansible.builtin.package:
      name: fonts-firacode
      state: present

  - name: Ensure MC is installed
    ansible.builtin.package: 
      name: mc
      state: present

  - name: Ensure Python is installed
    ansible.builtin.package:
      name: python3
      state: present
  
  - name: Ensure PIP is installed
    ansible.builtin.package:
      name: python3-pip
      state: present

  - name: Ensure OpenSSH Server is installed
    ansible.builtin.package:
      name: openssh-server
      state: present

  - name: Ensure OpenSSH Client is installed
    ansible.builtin.package:
      name: openssh-client
      state: present

# clone dotfiles
# setup symlink
# setup wireguard
