- hosts: app
  become: yes

  pre_tasks:
  - name: Update apt cache if needed
    apt:
      update_cache: true
      cache_valid_time: 3600

  tasks:
  - name: Ensure Universe Repo is enabled
    apt_repository:
      repo: deb http://archive.ubuntu.com/ubuntu focal universe
      state: present
      update_cache: true

  - name: Ensure ZSH is installed
    package:
      name: zsh
      state: present

  - name: Ensure git is installed
    apt: 
      name: git
      state: present

  - name: Ensure curl is installed
    apt:
      name: curl
      state: present

  - name: Ensure wget is installed
    apt:
      name: wget
      state: present

  - name: Ensure FiraCode is installed
    apt:
      name: fonts-firacode
      state: present

  - name: Ensure MC is installed
    apt: 
      name: mc
      state: present

  - name: Ensure Python is installed
    apt:
      name: python3
      state: present
  
  - name: Ensure PIP is installed
    apt:
      name: python3-pip
      state: present


# install docker
# clone dotfiles
# setup symlink
# setup wireguard
